#!/bin/bash
# Run "/etc/X11/xinit/xinitrc.d/" Process
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for i in /etc/X11/xinit/xinitrc.d/*; do
        if [ -x "$i" ]; then
            . "$i"
        fi
    done
fi

xset m 1 5

if [ -f $HOME/.xmodmap ]; then
  /usr/bin/xmodmap $HOME/.xmodmap
fi

# compton -cCG -o 0.1 -f 0.05 -t 0.01 -l 0.01 -r 2.5 -D 2 &
xset r rate 200 50

# exec startxfce4
exec awesome
# exec startkde
#
