(require 'prelude-c)
(require 'prelude-clojure)
(require 'prelude-common-lisp)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
(require 'prelude-lisp)
(require 'prelude-erc)
(require 'prelude-org)
;; (require 'prelude-markdown)
(require 'prelude-perl)
(require 'prelude-js)
(require 'prelude-scheme)
(require 'prelude-ruby)
(require 'prelude-python)
(require 'prelude-scss)
(require 'prelude-xml)
