#!/usr/bin/env bash

[[ -s $HOME/.bashrc_gentoo_before ]] && . $HOME/.bashrc_gentoo_before

if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi


# Put your fun stuff here.

if [ "$PS1" ]; then
    complete -cf sudo
fi

# export PATH var
export PATH=$PATH:~/bin

# set default editor
export EDITOR=/usr/bin/nano

# aliases
alias ll='ls -lAFh'
alias grep='grep --color'
alias ls='ls --color=auto'
alias l='ls --color=auto'
alias mysql='mysql --default-character-set=utf8 --auto-rehash'
alias ssh='ssh -A'
alias vim='emacsclient -t'
alias vi='emacsclient -t'
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias ed='emacs --daemon'

# mutt
MAIL=/var/spool/mail/aleiphoenix && export MAIL

# # for chromium swithy!
# export GNOME_DESKTOP_SESSION_ID=Default

export HISTCONTROL=ignoreboth
export HISTSIZE=1000000

# normal PS1
export PS1="\u@\h \W \$ "

# nodejs
export NODE_PATH="/usr/lib/node_modules"

# pythonbrew
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

# perlbrew
[[ -s $HOME/perl5/perlbrew/etc/bashrc ]] && source $HOME/perl5/perlbrew/etc/bashrc

# rvm
# [[ -s $HOME/.rvm/scripts/rvm ]] && . $HOME/.rvm/scripts/rvm && unset RUBYOPT

# load functions
. $HOME/.bash_functions

if [[ -d $HOME/.pyenv ]]; then
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
fi
if [[ -d $HOME/.rbenv ]]; then
  export PATH="$HOME/.rbenv/bin/:$PATH"
  eval "$(rbenv init -)"
fi

# PS1='\[\e[1;32m\]θ\[\e[m\] ' # host
if [[ $UID == 0 ]]; then
  PS1='\[\e[1;31m\]\h\[\e[m\] ' # host
else
  PS1='\[\e[1;32m\]\h\[\e[m\] ' # host
fi
PS1=$PS1'\[\e[1;34m\]\W\[\e[m\] ' # wd
if [[ -n "$(command -v rbenv)" ]]; then
  PS1=$PS1'\[\e[1;33m\]$(__rbenv_ps1)\[\e[m\]' # rbenv version
fi
if [[ $(function_exists __git_ps1) == 'function' ]]; then
  PS1=$PS1'\[\e[1;32m\]$(__parse_git)\[\e[m\]' # git
fi
export PS1

# if [ -f $HOME/.keychain/$HOSTNAME-sh ]; then
#     /usr/bin/keychain -q $HOME/.ssh/id_rsa
#     . $HOME/.keychain/$HOSTNAME-sh
# fi
unset RUBYOPT

# for tmux-powerline
if [[ -n $(command -v tmux) ]]; then
  [[ -n $TMUX ]] && export TERM="screen-256color"
  alias tmux="tmux -2"
fi

[[ -s $HOME/.bashrc_gentoo_after ]] && . $HOME/.bashrc_gentoo_after
