#!/usr/bin/env bash
# Check for an interactive session
# [[ $- != *i* ]] && exit

# path
PATH="/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH"

# CHOST for Mac OS X
export CHOST="x86_64-apple-darwin12"

if [[ -n "$PS1" ]]; then
    complete -cf sudo
fi

# homebrew
export HOMEBREW_TEMP="/usr/local/tmp"

# bash completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

# color for ls in terminal
export CLICOLOR=1

# alias
alias ll='ls -lAFhG'
alias grep='grep --color'
alias ls="ls"
alias l='ls'
alias ssh='ssh -A'
alias tmux='/usr/bin/env tmux -2'
alias memacs='~/Applications/Emacs.app/Contents/MacOS/Emacs'
alias e="emacsclient -t"
alias ec="emacsclient -c"
alias ed="emacs --daemon"
alias z="zile"

[[ -n "$(command -v mvim)" ]] && alias vim="mvim" && alias vi="mvim -v"

export NODE_PATH="/usr/local/lib/node_modules"

# export EDITOR="mvim"
export EDITOR="e"

export HISTCONTROL=ignoredups:ignorespace
shopt -s histappend
export HISTSIZE="10000000"
shopt -s checkwinsize

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# basic PS1
export PS1="\h \W \$ "

[ -f $HOME/.bash_functions ] && . $HOME/.bash_functions

if [ $(function_exists __git_ps1) == 'function' ]; then
    PS1='\[\e[1;31m\]θ\[\e[m\] ' # host
    PS1=$PS1'\[\e[1;34m\]\W\[\e[m\] ' # wd
    PS1=$PS1'\[\e[1;33m\]$(__rbenv_ps1)\[\e[m\]' # rbenv
    PS1=$PS1'\[\e[1;32m\]$(__parse_git)\[\e[m\]' # git
    export PS1
fi

[[ -s $HOME/.bashrc_mac_after ]] && . $HOME/.bashrc_mac_after
