#!/usr/bin/env bash

[[ -s $HOME/.bashrc_gentoo_before ]] && . $HOME/.bashrc_gentoo_before

if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi


# Put your fun stuff here.

if [ "$PS1" ]; then
    complete -cf sudo
fi

# export default input method
export GTK_IM_MODULE=scim
export XMODIFIERS=@im=SCIM
export QT_IM_MODULE=scim

# export PATH var
export PATH=$PATH:~/bin

# set default editor
export EDITOR=/usr/bin/vim

# aliases
alias ll='ls -lAFh'
alias grep='grep --color'
alias ls='ls --color=auto'
alias l='ls --color=auto'
alias mysql='mysql --default-character-set=utf8 --auto-rehash'
alias ssh='ssh -A'
alias em='emacs'

# mutt
MAIL=/var/spool/mail/aleiphoenix && export MAIL

# # for chromium swithy!
# export GNOME_DESKTOP_SESSION_ID=Default

export HISTCONTROL=ingoreboth
export HISTSIZE=1000000

# normal PS1
export PS1="\u@\h \W \$ "

# nodejs
export NODE_PATH="/usr/local/lib/node_modules"

# rvm
[[ -s $HOME/.rvm/scripts/rvm ]] && . $HOME/.rvm/scripts/rvm && unset RUBYOPT

# pythonbrew
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

# load functions
. $HOME/.bash_functions


if [ $(function_exists __git_ps1) == 'function' ]; then
  PS1='\[\e[1;32m\]$(is_root)\[\e[m\]' # root?
  PS1=$PS1'\[\e[1;31m\]\h\[\e[m\] ' # host
  PS1=$PS1'\[\e[1;34m\]\W\[\e[m\] ' # wd
  PS1=$PS1'\[\e[1;33m\]$(__ruby_version)\[\e[m\]' # rvm version
  PS1=$PS1'\[\e[1;32m\]$(__git_ps1)\[\e[m\] ' # git
  export PS1
fi



# if [ -f $HOME/.keychain/$HOSTNAME-sh ]; then
#     /usr/bin/keychain -q $HOME/.ssh/id_rsa
#     . $HOME/.keychain/$HOSTNAME-sh
# fi

# for tmux-powerline
if [[ -n $(command -v tmux) ]]; then
  [[ -n $TMUX ]] && export TERM="screen-256color"
  alias tmux="tmux -2"
  export PLATFORM="linux"
  export PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#I_#P") "$PWD")'
fi

[[ -s $HOME/.bashrc_gentoo_after ]] && . $HOME/.bashrc_gentoo_after
